import os
import re
from pathlib import Path
from src.config import load_manifest, load_state, KIT_DIR, load_local_state, get_active_profile
from src.mcp import get_mcp_states, check_mcp_health
from src.pruner import get_profile_keywords
from adapters import ALL_ADAPTERS

def setup_env_interactive():
    print("\033[1;36m🔑 mykit MCP Secret & API Key Interactive Setup Wizard\033[0m\n")
    manifest = load_manifest()
    mcps = manifest.get("global", {}).get("mcp_servers", {})

    needed_vars = set()
    for name, conf in mcps.items():
        env_dict = conf.get("env", {})
        for k, v in env_dict.items():
            match = re.search(r'\$\{([^}]+)\}', str(v))
            if match:
                needed_vars.add(match.group(1))

    env_file = KIT_DIR / ".env"
    existing_env = {}
    if env_file.exists():
        with open(env_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    k, v = line.split('=', 1)
                    existing_env[k.strip()] = v.strip().strip('"\'')

    updated_env = dict(existing_env)
    print("Please enter values for required API keys (Press Enter to keep current value):\n")

    for var in sorted(needed_vars):
        curr = existing_env.get(var, "")
        curr_display = f" [Current: {curr[:6]}...{curr[-4:]}]" if len(curr) > 10 else f" [Current: {curr}]" if curr else " [Not Set]"
        
        val = input(f"👉 \033[1m{var}\033[0m{curr_display}: ").strip()
        if val:
            updated_env[var] = val
        elif var not in updated_env:
            updated_env[var] = ""

    # Write back to .env
    with open(env_file, 'w', encoding='utf-8') as f:
        f.write("# my-ai-kit Environment Secrets File\n")
        f.write("# Automatically generated by mykit env setup\n\n")
        for k, v in sorted(updated_env.items()):
            f.write(f"{k}={v}\n")

    print(f"\n\033[1;32m✓ Saved secrets to {env_file} successfully!\033[0m\n")

def show_stats():
    manifest = load_manifest()
    active_profile = get_active_profile()
    active_mcps, disabled_mcps = get_mcp_states()
    
    ecc_base = Path("~/.claude/plugins/cache/ecc/ecc/2.0.0/skills").expanduser()
    ecc_total_cnt = len(list(ecc_base.glob("*"))) if ecc_base.exists() else 271
    
    pruned_dir = Path("~/.agent-skills/store/ecc-pruned-skills").expanduser()
    loaded_cnt = len(list(pruned_dir.glob("*"))) if pruned_dir.exists() else 92
    
    reduction_pct = ((ecc_total_cnt - loaded_cnt) / ecc_total_cnt * 100) if ecc_total_cnt > 0 else 0
    saved_tokens = (ecc_total_cnt - loaded_cnt) * 30  # Avg 30 tokens per skill metadata line

    agents_dir = KIT_DIR / "agents"
    agents_cnt = len(list(agents_dir.glob("*.md"))) if agents_dir.exists() else 0

    print("┌──────────────────────────────────────────────────────────────┐")
    print("│         \033[1;36m🧰 my-ai-kit System & Performance Analytics\033[0m        │")
    print("├──────────────────────────────────────────────────────────────┤")
    print(f"│  • Active Profile: \033[1;32m{active_profile:<12}\033[0m                             │")
    print(f"│  • Total Original Skills: \033[1m{ecc_total_cnt:<5}\033[0m                               │")
    print(f"│  • Profile Filtered Skills: \033[1;32m{loaded_cnt:<5}\033[0m                             │")
    print(f"│  • Skill Reduction Rate: \033[1;33m{reduction_pct:.1f}%\033[0m                                 │")
    print(f"│  • Est. Token Savings: \033[1;32m~{saved_tokens:,} Tokens / Session\033[0m          │")
    print("├──────────────────────────────────────────────────────────────┤")
    print(f"│  • Active MCP Servers: \033[1;32m{len(active_mcps):<2}\033[0m / {len(active_mcps) + len(disabled_mcps):<2} (Disabled: {len(disabled_mcps)})               │")
    print(f"│  • Custom Subagents: \033[1;35m{agents_cnt:<2} personas (agents/*.md)\033[0m                 │")
    print("├──────────────────────────────────────────────────────────────┤")
    print("│  \033[1;34m[Connected Target Adapters]\033[0m                                 │")
    for adapter in ALL_ADAPTERS:
        g_dir = adapter.ensure_target_dir(is_local=False)
        ag_dir = adapter.ensure_agent_target_dir(is_local=False)
        cnt_s = len(list(g_dir.glob("*")))
        cnt_a = len(list(ag_dir.glob("*")))
        print(f"│  ✓ {adapter.name:<18} -> {cnt_s:<3} skills | {cnt_a:<2} agents          │")
    print("└──────────────────────────────────────────────────────────────┘")
